version: '3'
services:
  movies:
    image: jayasri1928/moviespaytm:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: jayasri1928/trainpaytm:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: jayasri1928/dthpaytm:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  recharge:
    image: jayasri1928/rechargepaytm:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
